// elementos del DOM
console.log('document', document)
console.log('head', document.head)
console.log('body', document.body)
console.log('documentElement', document.documentElement)
console.log('doctype', document.doctype)
console.log('title', document.title)
console.log('links', document.links)
console.log('images', document.images)
console.log('forms', document.forms)
console.log('styleSheets', document.styleSheets)
console.log('scripts', document.scripts)
document.write('<h1>Escribiendo desde javascript</h1>')
